correct a bug in workflow

diff --git a/.github/workflows/check-lint.yml b/.github/workflows/check-lint.yml
--- a/.github/workflows/check-lint.yml
+++ b/.github/workflows/check-lint.yml
@@ -66,3 +66,15 @@ jobs:
           fi
 
       - run: echo "🍏 This job's status is ${{ job.status }}."
+
+  lint-ok:
+    needs: lint
+    runs-on: ubuntu-latest
+    if: always()
+    steps:
+      - name: All lint checks passed
+        run: |
+          if [[ "${{ needs.lint.result }}" != "success" ]]; then
+            echo "lint job failed or was cancelled"
+            exit 1
+          fi
diff --git a/.github/workflows/check-test.yml b/.github/workflows/check-test.yml
--- a/.github/workflows/check-test.yml
+++ b/.github/workflows/check-test.yml
@@ -66,3 +66,15 @@ jobs:
         run: pytest -v
 
       - run: echo "🍏 This job's status is ${{ job.status }}."
+
+  test-ok:
+    needs: test
+    runs-on: ubuntu-latest
+    if: always()
+    steps:
+      - name: All test checks passed
+        run: |
+          if [[ "${{ needs.test.result }}" != "success" ]]; then
+            echo "test job failed or was cancelled"
+            exit 1
+          fi
diff --git a/.github/workflows/check-type.yml b/.github/workflows/check-type.yml
--- a/.github/workflows/check-type.yml
+++ b/.github/workflows/check-type.yml
@@ -56,3 +56,15 @@ jobs:
         run: mypy
 
       - run: echo "🍏 This job's status is ${{ job.status }}."
+
+  type-ok:
+    needs: type
+    runs-on: ubuntu-latest
+    if: always()
+    steps:
+      - name: All type checks passed
+        run: |
+          if [[ "${{ needs.type.result }}" != "success" ]]; then
+            echo "type job failed or was cancelled"
+            exit 1
+          fi
